### PR TITLE
Use new FSM payload and JSON editor to build message

### PR DESCRIPTION
**Pull request by clemdesign**
Hi,

First thanks for your great tool !

I propose the following modifications:
- Use new [FSM notification payload](https://firebase.google.com/docs/cloud-messaging/http-server-ref) including `notification` field and `data` field 
- Use the following JSON editor to build message: https://github.com/AndrewRedican/react-json-editor-ajrm

I tested the tool for iOS and Android and works.

Thank you for considering this improvment :)

Best !

### CODE REVIEW

**Comment by Ariandr** [comment]
Hi @clemdesign 
Thanks for your PR 👍 
I looked into the changes, they seem okay. And they are mainly for Android. For iOS you've just changed the editor, right?

I believe @onmyway133 should also review the changes and if everything is approved we will merge it and create a new release.

**Comment by Ariandr** [comment]
Also, before creating a new release I will test iOS part on my side just to be sure, since ~90% of users use this tool for sendingiOS notifications.

**Comment by onmyway133** [comment]
@clemdesign thanks for the PR, and thanks @Ariandr for reviewing. I just check the code, looks good, but I need to check and run it first before I can merge.

**Comment by clemdesign** [comment]
@Ariandr , yes, changes concern mainly Android (FSM and editor). On iOS, changes concern only the editor.
Yeah, to test notifications I used this tool for iOS and Postman for Android, but I think that if the same tool can be used for both platforms, it is better.

@onmyway133 Okay :)

**Comment by onmyway133** [comment]
Hei, I take a look and it seems OK. The new editor seems fancy but one thing I'm a bit worried is it has some reported issues https://github.com/AndrewRedican/react-json-editor-ajrm/issues

But overall, great PR @clemdesign 👍 

Screenshot 2020-12-10 at 05 47 35

**Comment by clemdesign** [comment]
Oh you're right about some reported issues. I focused on making friendly the editor that I forgot to check issues.  
I did some test (edition, copy, paste...) and works but maybe for certain situation, the plugin does not work.  
So, I think possibilities are :
- not embed the new editor
- add option to offer possibility to use TextPlain editor or JSON editor
- embed the JSON editor and trust that for the use of the tool, it is acceptable

**Comment by onmyway133** [comment]
@clemdesign for now it looks OK, I'm fine with going with it. If it has many issues then we can remove it later.

**Comment by Ariandr** [comment]
I will create a release with the updates.

**Comment by Ariandr** [comment]
New release: https://github.com/onmyway133/PushNotifications/releases/tag/1.8.0

**Comment by Ariandr** [comment]
@clemdesign @onmyway133 
I deleted the release. I started doing some specific activities and found it difficult to fight with this JSON editor. It would constantly jump on the first line and show an error even when I want to insert a simple string.

**Pull request merged**
