### PR TITLE
Adding support for Linux and Windows platforms

### PR DESCRIPTION
**Pull request by Ariandr**
To build the Mac version, you will just need run `npm run dist` on your mac, which will create a `dist` directory with build files and the app.

Here is the link to .zip with Windows and Linux built versions/installers of the app.
https://drive.google.com/file/d/1K1og5oMmh79iLEvy1dp2mc8vvfmdCbAX/view?usp=sharing

screenshot at aug 01 15-29-35
screenshot at aug 01 15-32-07

### CODE REVIEW

**Comment by onmyway133** [comment]
@Ariandr 3465 file changes 😅 looks fine to me. Thanks for the PR 🚀

**Comment by Ariandr** [comment]
@onmyway133 
I just updated dependencies and modified `package.json`😀

**Comment by Ariandr** [comment]
@onmyway133 
By the way, I think it's important to update the description of the project (now it includes support for Windows & Linux) and add new release with installers for Linux and Windows 🙂

**Comment by Ariandr** [comment]
@onmyway133 
Also, it's probably fixes the issue #5 , because I updated `electron` to the latest version.

**Comment by onmyway133** [comment]
@Ariandr Hi, I just released 1.3.0 https://github.com/onmyway133/PushNotifications/releases/tag/1.3.0

**Comment by Ariandr** [comment]
@onmyway133 Will you add installers v.1.3.0 for Windows and Linux platforms to the release description, if I provide you with them?
I have just built v.1.3.0 for Windows and Linux.

**Comment by onmyway133** [comment]
@Ariandr Hi, I have another idea. Would you like to be contributor in this project? There you can manage releases, and we can collaborate together

**Comment by Ariandr** [comment]
@onmyway133 Yes. It sounds great. I'd like to become a contributor 🙂
I don't have and experience in managing releases on Github, but I think I will work it out))

**Comment by onmyway133** [comment]
@Ariandr Check your email 😉 . Don't worry, that's how we grow 💪

**Comment by Ariandr** [comment]
@onmyway133 Thanks, I've accepted.🙂

**Comment by Ariandr** [comment]
@onmyway133 Great!

**Comment by onmyway133** [comment]
@Ariandr Hi, how did you generate builds for Linux and Windows? I run `npm run dist` and it generates for macOS only

**Comment by Ariandr** [comment]
@onmyway133 You need to run that command on Windows and Linux machines separately 🙂
I have an old Windows laptop at work and for Linux I used a cloud service for building.

**Comment by Ariandr** [comment]
@onmyway133 Also I made sure that the node & npm versions were the same on all the platforms.

**Pull request merged**
