### PR TITLE
Adding support for iOS Live Activity push notifications

### PR DESCRIPTION
**Pull request by mvandervelden**
## Background
As mentioned in these [Apple Docs](https://developer.apple.com/documentation/activitykit/update-and-end-your-live-activity-with-remote-push-notifications) about the upcoming Live Activities feature. This feature will support using APNs push notifications, for which some specific headers are required: 
- The `apns-topic` header should have the format `<your bundleID>.push-type.liveactivity`
- The `apns-push-type` header should be `liveactivity`.

## This PR
With this change, the Push Notifications app should support this new type of notifications, if users provide the correct apns-topic as bundleId (`<your bundleID>.push-type.liveactivity`).

Let me know if anything in the PR requires changing. This set up seems to work for me locally.

### CODE REVIEW

**Comment by Ariandr** [comment]
Hi @mvandervelden 
Thank you for this PR.

The code change is straightforward, so If you tested and it works, I'll create a new release with this change.

**Review by Ariandr — APPROVED** [review]
lgtm

**Comment by mvandervelden** [comment]
@Ariandr thanks for approving and merging! 🙇

**Comment by Ariandr** [comment]
@mvandervelden always happy to see people contributing❤️

**Pull request merged**
