### PR TITLE
Fix Android payload structure to let device receive proper push notification.

### PR DESCRIPTION
**Pull request by buleglay**

### CODE REVIEW

**Comment by Ariandr** [comment]
Hi @buleglay 
Thanks for PR.
Have you tested the update yourself?

**Comment by buleglay** [comment]
> Hi @buleglay
> Thanks for PR.
> Have you tested the update yourself?

Hi @Ariandr,

Thanks for checking.

The change has been tested on an OnePlus phone.

The issue was that Android devices won't be able to properly handle the push notification if both title & message was placed inside `data` object therefore nothing would show up.

According to this Firebase doc: https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json, `data` is used for custom key-value pairs, while `notification` is for user-visible key-values pairs (in this case, title and message).

Hope it makes sense.

Regards,
Sean

**Comment by Ariandr** [comment]
@buleglay 
It looks good to me, though I don't have Android device or environment to test it myself.

Hi @onmyway133 
What do you think? I believe we can merge it, because the changes are pretty straightforward.

**Comment by buleglay** [comment]
> @buleglay
> It looks good to me, though I don't have Android device or environment to test it myself.
> 
> Hi @onmyway133
> What do you think? I believe we can merge it, because the changes are pretty straightforward.

This won’t be a “breaking change” to the existing users who’s currently relying on it to test their push notifications.

As they will still get the same data property containing the payload they’re currently sending, plus an additional notification property which would trigger native level push notifications.

**Comment by Ariandr** [comment]
@buleglay 
I agree.
If @onmyway133 confirms, I will create a new release.

**Comment by onmyway133** [comment]
Thanks for the PR @buleglay and thanks for checking @Ariandr , I've checked the changes and it looks good to me 👍

**Comment by Ariandr** [comment]
@onmyway133 
Great. I merged it and will create a new release🙂

**Comment by Ariandr** [comment]
@buleglay 
Have a look at the release version please: https://github.com/onmyway133/PushNotifications/releases/tag/1.7.8

**Comment by buleglay** [comment]
LGTM!

Thanks guys! @Ariandr @onmyway133

**Pull request merged**
