### PR TITLE
Fix android push

### PR DESCRIPTION
**Pull request by atsushi-ageet**
Currently Android Push seems to always fail.
I analyzed and fixed the problem.

### CODE REVIEW

**Comment by onmyway133** [comment]
@atsushi-ageet awesome 👍

**Comment by alexcosmin** [comment]
@onmyway133 would it be possible to make a new release with this fix, so Android Push would work in the latest release? :)

**Comment by Timo-Linde** [comment]
You can build this on your own:
Checkout the Repository
Install yarn (i did it with homebrew): `brew install yarn`
Add the electron-builder: `yarn add electron-builder --dev`
I needed to run the yarn add electron-builder command twice, dont know why
cd in the directory and run `yarn dist`

This worked for me

**Comment by onmyway133** [comment]
@atsushi-ageet @alexcosmin Hi, sorry for late reply, I just built it and made new release 1.4.0 https://github.com/onmyway133/PushNotifications/releases/tag/1.4.0

**Pull request merged**
